### ISSUE TITLE
Sprint1 Checklist

### ISSUE THREAD

**Issue by rahulverma13** [aaguy-hue/aadit_2025#2]
- [X] **Laptop Verification or Cloud Workspace**
  - Rank: 4
  - Notes: verification by Linux commands notebook

- [X] **VSCode**
  - Rank: 4
  - Notes: live change code, commit, make, run localhost, test, debug

- [X] **Show VSCode GitLens**
  - Rank: 3
  - Notes: verify commits, show change, comments, reset to commit, run on old commit

- [X] **GitHub cloud repo**
  - Rank: 4
  - Notes: live push change, verify id, review profile

- [X] **GitHub Pages Actions**
  - Rank: 4
  - Notes: review runs and verify runtime, receive demo

- [X] **Hacks Tools & Equipment Play**
  - Rank: 4
  - Notes:

- [X] **Hacks GitHub Pages Playground**
  - Rank: 4
  - Notes:

- [X] **Hacks SASS Basics**
  - Rank: 2
  - Notes:

- [X] **Hacks Jupyter Notebook**
  - Rank: 3
  - Notes:

- [X] **Pair Programming**
  - Rank: 4
  - Notes: tangibles that show co-operative work, used VSCode liveshare to create Sorting Simulator

_Originally posted by @jm1021 in https://github.com/nighthawkcoders/portfolio_2025/issues/14#issuecomment-2237380182_

**Comment by rahulverma13** [comment]
- [X] **Attendance**
  - Rank: 3
  - Notes: 

- [X] **Work Habits**
  - Rank: 4
  - Notes: 

- [X] **Behavior**
  - Rank: 4
  - Notes: 

- [X] **Timeliness**
  - Rank: 3
  - Notes: 

- [X] **Tech Sense**
  - Rank: 4
  - Notes: 

- [X] **Tech Talk**
  - Rank: 4
  - Notes: 

- [X] **Tech Growth**
  - Rank: 3
  - Notes: 

- [X] **Advocacy**
  - Rank: 4
  - Notes: 

- [X] **Comm & Collab**
  - Rank: 4
  - Notes: 

- [X] **Integrity**
  - Rank: 4
  - Notes: 

- [X] **Organized**
  - Rank: 3
  - Notes:

_Originally posted by @jm1021 in https://github.com/nighthawkcoders/portfolio_2025/issues/14#issuecomment-2237421557_
